const domain = "http://localhost:3004/api"
const accountAPI = domain + "/account"
const orderAPI = domain + "/order"
const productAPI = domain + "/product"
const brandAPI = domain + "/brand"
const categoryAPI = domain + "/category"
const favoriteAPI = domain + "/favourites"
const promocodeAPI = domain + "/promocode"
