const domain = "http://localhost:3004"
const accountAPI = domain + "/api/account"
const orderAPI = domain + "/api/order"
const productAPI = domain + "/api/product"
const brandAPI = domain + "/api/brand"
const categoryAPI = domain + "/api/category"
const favoriteAPI = domain + "/api/favourites"
const promocodeAPI = domain + "/api/promocode"
